receivers:
  filelog/postgres:
    include: ["/var/lib/postgresql/data/log/postgresql.log"]  # Adjust based on actual container volume
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>[^ ]+) \[(?P<pid>\d+)\] (?P<user>\w+)@(?P<db>\w+): (?P<log_level>\w+): (?P<message>.*)'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%d %H:%M:%S.%L %Z'
      - type: move
        from: attributes.message
        to: body
      - type: remove
        field: attributes.timestamp

  sqlquery:
    driver: "postgres"
    datasource: "host=host.docker.internal port=5432 user=lcbo password=Secret5555 dbname=lcbo sslmode=disable"
    queries:
      - sql: "SELECT COUNT(*) AS user_count FROM users"
        metrics:
          - metric_name: "custom.postgres.user_count"
            value_column: "user_count"
            value_type: "gauge"
            data_type: "int"

  postgresql:
    endpoint: "host.docker.internal:5432"
    username: "postgres"
    password: "postgres"
    database: "lcbo"
    tls:
      insecure: true

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

exporters:
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true

  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

service:
  telemetry:
    logs:
      encoding: json
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    metrics:
      receivers: [otlp, postgresql, sqlquery]
      processors: [batch]
      exporters: [clickhousemetricswrite]

    logs:
      receivers: [filelog/postgres]
      processors: [batch]
      exporters: [clickhouselogsexporter]
