  filelog/postgres:
    include:
      - /var/lib/docker/containers/*/*.log
    include_file_path: true
    include_file_name: true
    start_at: beginning
    operators:
      - type: json_parser
        id: parse-json
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        severity:
          parse_from: attributes.level
        message:
          parse_from: attributes.log
      - type: move
        from: attributes.log
        to: body
      - type: filter
        expr: 'body contains "postgres"'

  sqlquery:
    driver: "postgres"
    datasource: "host=host.docker.internal port=5432 user=lcbo password=Secret5555 dbname=lcbo sslmode=disable"
    queries:
      - sql: "SELECT COUNT(*) AS user_count FROM users"
        metrics:
          - metric_name: "custom.postgres.user_count"
            value_column: "user_count"
            value_type: "gauge"
            data_type: "int"

  postgresql:
    endpoint: "host.docker.internal:5432"
    username: "postgres"
    password: "postgres"
    database: "lcbo"
    tls:
      insecure: true

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

exporters:
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true

  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

service:
  telemetry:
    logs:
      encoding: json
    metrics:
      address: 0.0.0.0:8888


  pipelines:
     pipelines:
    logs:
      receivers: [otlp, tcplog/docker, filelog/postgres]
      processors: [batch]
      exporters: [clickhouselogsexporter]


    metrics:
      receivers: [otlp, postgresql, sqlquery]
      processors: [batch]
      exporters: [clickhousemetricswrite]

  